webcams:
    -
        name: 'cam_01'
        port: '/dev/video0'
    -
        name: 'cam_02'
        port: '/dev/video1'
directories:
    images: '/var/panoptes/images'
    webcam: '/var/panoptes/webcams'
    data: '/var/panoptes/data'
environment:
    auto_detect: True
weather:
    station: mongo
    web_service:
      name: 'aat-metdata'
      link: 'ftp://site-ftp.aao.gov.au/pub/local/metdata/metdata1.dat'
      column_names:  ['Time (UTC)',
                      'outside_air_temperature',
                      'dome_air_temperature',
                      'mirror_temperature',
                      'dome_dewpoint',
                      'outside_humidity',
                      'barometric_pressure',
                      'wind_speed',
                      'wind_gust',
                      'wind_direction',
                      'dome_door_status', # closed = 0 | partially open = 2 | open = 4
                      'rain_sensor', # no rain = 0 | rain > 0
                      'outside_dewpoint',
                      'sky-ambient',
                      'sky-ambient_uncertainty',
                      'boltwood_sky_brightness', # dark = 0 | light > 0
                      'boltwood_rain_flag', # no rain = 0 | rain > 0
                      'boltwood_wet_flag', # dry = 0 | wet > 0
                      'rain_since_9am',
                      'SQM_sky_brightness']
      # be sure to have the same number of entries in column_names and column_units
      column_units:  [u.dimensionless_unscaled,
                      u.Celsius,
                      u.Celsius,
                      u.Celsius,
                      u.Celsius,
                      u.percent,
                      cds.mmHg,
                      u.km / u.hour,
                      u.km / u.hour,
                      u.degree,
                      u.dimensionless_unscaled,
                      u.dimensionless_unscaled,
                      u.Celsius,
                      u.Celsius,
                      u.Celsius,
                      u.dimensionless_unscaled,
                      u.dimensionless_unscaled,
                      u.dimensionless_unscaled,
                      u.mm,
                      u.ABmag]
      max_age: 60.
      thresholds:
        sky-ambient:
          clear: -.inf, -25
          cloudy: -25., -15.
          very_cloudy: -15., .inf
        wind_speed:
          calm: 0., 50.
          windy: 50., 75.
          very_windy: 75., .inf
        wind_gust:
          calm: 0., 100.
          gusty: 100., 125.
          very_gusty: 125., .inf
        rain_sensor:
          no_data: -1
          no_rain: 0
          rain: 1
        boltwood_rain_flag:
          no_data: -1
          no_rain: 0
          rain: 1
        boltwood_wet_flag:
          no_data: -1
          dry: 0
          wet: 1
    aag_cloud:
        name: 'aag-cloudsensor'
        serial_port: '/dev/ttyUSB1'
        heater:
            low_temp: 0 ## deg C
            low_delta: 6 ## deg C
            high_temp: 20 ## deg C
            high_delta: 4 ## deg C
            min_power: 10 ## percent
            impulse_temp: 10 ## deg C
            impulse_duration: 60 ## seconds
            impulse_cycle: 600 ## seconds
        thresholds:
          sky-ambient:
            clear: -.inf, -25
            cloudy: -25., -15.
            very_cloudy: -15., .inf
          wind_speed:
            calm: 0., 50.
            windy: 50., 75.
            very_windy: 75., .inf
          wind_gust:
            calm: 0., 100.
            gusty: 100., 125.
            very_gusty: 125., .inf
          rain_frequency:
            dry: 2200., .inf
            wet: 1800., 2200.
            rainy: 0, 1800.
    plot:
        amb_temp_limits: [-5, 35]
        cloudiness_limits: [-45, 5]
        wind_limits: [0, 75]
        rain_limits: [700, 3200]
        pwm_limits: [-5, 105]
    safety_delay: 15. ## minutes
