webcams:
    -
        name: 'cam_01'
        port: '/dev/video0'
    -
        name: 'cam_02'
        port: '/dev/video1'
directories:
    images: '/var/panoptes/images'
    webcam: '/var/panoptes/webcams'
    data: '/var/panoptes/data'
environment:
    auto_detect: True
weather:
    station: mongo
    web_service:
      name: 'AAT met data'
      link: 'ftp://site-ftp.aao.gov.au/pub/local/metdata/metdata1.dat'
      column_names:  ['Time (UTC)',
                      'Outside air temperature',
                      'AAT dome air temperature',
                      'AAT mirror temperature',
                      'AAT dome dewpoint',
                      'Outside humidity',
                      'Barometric pressure',
                      'Wind speed',
                      'Wind gust',
                      'Wind direction',
                      'AAT dome door status', # closed = 0 | partially open = 2 | open = 4
                      'Rain sensor', # no rain = 0 | rain > 0
                      'Outside dewpoint',
                      'Sky-ambient',
                      'Sky-ambient uncertainty',
                      'Boltwood sky brightness', # dark = 0 | light > 0
                      'Boltwood rain flag', # no rain = 0 | rain > 0
                      'Boltwood wet flag', # dry = 0 | wet > 0
                      'Rain since 9am',
                      'SQM sky brightness']
      # be sure to have the same number of entries in column_names and column_units
      column_units:  [u.dimensionless_unscaled,
                      u.Celsius,
                      u.Celsius,
                      u.Celsius,
                      u.Celsius,
                      u.percent,
                      cds.mmHg,
                      u.km / u.hour,
                      u.km / u.hour,
                      u.degree,
                      u.dimensionless_unscaled,
                      u.dimensionless_unscaled,
                      u.Celsius,
                      u.Celsius,
                      u.Celsius,
                      u.dimensionless_unscaled,
                      u.dimensionless_unscaled,
                      u.dimensionless_unscaled,
                      u.mm,
                      u.ABmag]
      max_age: 60.
      thresholds:
        Sky-ambient:
          Clear:       [-.inf, 25.0]
          Cloudy:      [-25., -15.0]
          Very cloudy: [-15., 0]
        Wind speed:
          Calm:        [0.0, 50.0]
          Windy:       [50.0, 75.0]
          Very Windy:  [75.0, .inf]
        Wind gust:
          Calm:        [0.0, 100.0]
          Gusty:       [100.0, 125.0]
          Very gusty:  [125.0, .inf]
        Rain sensor:
          No data:     [-1]
          No rain:     [0]
          Rain:        [1]
        Boltwood rain flag:
          No data:     [-1]
          No rain:     [0]
          Rain:        [1]
        Boltwood wet flag:
          No data:     [-1]
          Dry:         [0]
          Wet:         [1]
    aag_cloud:
        name: 'AAG CloudWatcher'
        serial_port: 'COM4'
        threshold_cloudy: -25
        threshold_very_cloudy: -15.
        threshold_windy: 50.
        threshold_very_windy: 75.
        threshold_gusty: 100.
        threshold_very_gusty: 125.
        threshold_wet: 2200.
        threshold_rainy: 1800.
        safety_delay: 15 ## minutes
        heater:
            low_temp: 0 ## deg C
            low_delta: 6 ## deg C
            high_temp: 20 ## deg C
            high_delta: 4 ## deg C
            min_power: 10 ## percent
            impulse_temp: 10 ## deg C
            impulse_duration: 60 ## seconds
            impulse_cycle: 600 ## seconds
    plot:
        amb_temp_limits: [-5, 35]
        cloudiness_limits: [-45, 5]
        wind_limits: [0, 75]
        rain_limits: [700, 3200]
        pwm_limits: [-5, 105]
    safety_delay: 15. ## minutes
